# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime
import numpy as np
import csv
import pandas as pd
import math
import time
from numpy import genfromtxt
import xlsxwriter
import os



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 595)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 261, 521))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.cmbBox1 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox1.setObjectName("cmbBox1")
        self.cmbBox1.addItem("")
        self.cmbBox1.addItem("")
        self.cmbBox1.addItem("")
        self.cmbBox1.addItem("")
        self.cmbBox1.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cmbBox1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_2)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.cmbBox2 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox2.setObjectName("cmbBox2")
        self.cmbBox2.addItem("")
        self.cmbBox2.addItem("")
        self.cmbBox2.addItem("")
        self.cmbBox2.addItem("")
        self.cmbBox2.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.cmbBox2)
        self.cmbBox3 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox3.setObjectName("cmbBox3")
        self.cmbBox3.addItem("")
        self.cmbBox3.addItem("")
        self.cmbBox3.addItem("")
        self.cmbBox3.addItem("")
        self.cmbBox3.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cmbBox3)
        self.cmbBox4 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox4.setObjectName("cmbBox4")
        self.cmbBox4.addItem("")
        self.cmbBox4.addItem("")
        self.cmbBox4.addItem("")
        self.cmbBox4.addItem("")
        self.cmbBox4.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cmbBox4)
        self.cmbBox5 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox5.setObjectName("cmbBox5")
        self.cmbBox5.addItem("")
        self.cmbBox5.addItem("")
        self.cmbBox5.addItem("")
        self.cmbBox5.addItem("")
        self.cmbBox5.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cmbBox5)
        self.cmbBox6 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox6.setObjectName("cmbBox6")
        self.cmbBox6.addItem("")
        self.cmbBox6.addItem("")
        self.cmbBox6.addItem("")
        self.cmbBox6.addItem("")
        self.cmbBox6.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.cmbBox6)
        self.cmbBox7 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox7.setObjectName("cmbBox7")
        self.cmbBox7.addItem("")
        self.cmbBox7.addItem("")
        self.cmbBox7.addItem("")
        self.cmbBox7.addItem("")
        self.cmbBox7.addItem("")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cmbBox7)
        self.cmbBox8 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox8.setObjectName("cmbBox8")
        self.cmbBox8.addItem("")
        self.cmbBox8.addItem("")
        self.cmbBox8.addItem("")
        self.cmbBox8.addItem("")
        self.cmbBox8.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.cmbBox8)
        self.cmbBox9 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox9.setObjectName("cmbBox9")
        self.cmbBox9.addItem("")
        self.cmbBox9.addItem("")
        self.cmbBox9.addItem("")
        self.cmbBox9.addItem("")
        self.cmbBox9.addItem("")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.cmbBox9)
        self.cmbBox10 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox10.setObjectName("cmbBox10")
        self.cmbBox10.addItem("")
        self.cmbBox10.addItem("")
        self.cmbBox10.addItem("")
        self.cmbBox10.addItem("")
        self.cmbBox10.addItem("")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.cmbBox10)
        self.cmbBox11 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox11.setObjectName("cmbBox11")
        self.cmbBox11.addItem("")
        self.cmbBox11.addItem("")
        self.cmbBox11.addItem("")
        self.cmbBox11.addItem("")
        self.cmbBox11.addItem("")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.cmbBox11)
        self.cmbBox12 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox12.setObjectName("cmbBox12")
        self.cmbBox12.addItem("")
        self.cmbBox12.addItem("")
        self.cmbBox12.addItem("")
        self.cmbBox12.addItem("")
        self.cmbBox12.addItem("")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.cmbBox12)
        self.cmbBox13 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox13.setObjectName("cmbBox13")
        self.cmbBox13.addItem("")
        self.cmbBox13.addItem("")
        self.cmbBox13.addItem("")
        self.cmbBox13.addItem("")
        self.cmbBox13.addItem("")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.cmbBox13)
        self.cmbBox14 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox14.setObjectName("cmbBox14")
        self.cmbBox14.addItem("")
        self.cmbBox14.addItem("")
        self.cmbBox14.addItem("")
        self.cmbBox14.addItem("")
        self.cmbBox14.addItem("")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.cmbBox14)
        self.cmbBox15 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox15.setObjectName("cmbBox15")
        self.cmbBox15.addItem("")
        self.cmbBox15.addItem("")
        self.cmbBox15.addItem("")
        self.cmbBox15.addItem("")
        self.cmbBox15.addItem("")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.cmbBox15)
        self.cmbBox16 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox16.setObjectName("cmbBox16")
        self.cmbBox16.addItem("")
        self.cmbBox16.addItem("")
        self.cmbBox16.addItem("")
        self.cmbBox16.addItem("")
        self.cmbBox16.addItem("")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.FieldRole, self.cmbBox16)
        self.cmbBox17 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox17.setObjectName("cmbBox17")
        self.cmbBox17.addItem("")
        self.cmbBox17.addItem("")
        self.cmbBox17.addItem("")
        self.cmbBox17.addItem("")
        self.cmbBox17.addItem("")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.FieldRole, self.cmbBox17)
        self.cmbBox18 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox18.setObjectName("cmbBox18")
        self.cmbBox18.addItem("")
        self.cmbBox18.addItem("")
        self.cmbBox18.addItem("")
        self.cmbBox18.addItem("")
        self.cmbBox18.addItem("")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.FieldRole, self.cmbBox18)
        self.cmbBox19 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox19.setObjectName("cmbBox19")
        self.cmbBox19.addItem("")
        self.cmbBox19.addItem("")
        self.cmbBox19.addItem("")
        self.cmbBox19.addItem("")
        self.cmbBox19.addItem("")
        self.formLayout.setWidget(19, QtWidgets.QFormLayout.FieldRole, self.cmbBox19)
        self.cmbBox20 = QtWidgets.QComboBox(self.groupBox)
        self.cmbBox20.setObjectName("cmbBox20")
        self.cmbBox20.addItem("")
        self.cmbBox20.addItem("")
        self.cmbBox20.addItem("")
        self.cmbBox20.addItem("")
        self.cmbBox20.addItem("")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.cmbBox20)
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(260, 20, 521, 31))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(290, 60, 471, 31))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.rdoButton1 = QtWidgets.QRadioButton(self.centralwidget)
        self.rdoButton1.setGeometry(QtCore.QRect(300, 120, 82, 17))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.rdoButton1.setFont(font)
        self.rdoButton1.setChecked(True)
        self.rdoButton1.setObjectName("rdoButton1")
        self.rdoButton2 = QtWidgets.QRadioButton(self.centralwidget)
        self.rdoButton2.setGeometry(QtCore.QRect(400, 120, 82, 17))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.rdoButton2.setFont(font)
        self.rdoButton2.setObjectName("rdoButton2")
        self.btn_singles = QtWidgets.QPushButton(self.centralwidget)
        self.btn_singles.setGeometry(QtCore.QRect(290, 160, 241, 41))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.btn_singles.setFont(font)
        self.btn_singles.setObjectName("btn_singles")
        self.btn_calculte = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calculte.setGeometry(QtCore.QRect(340, 270, 201, 41))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.btn_calculte.setFont(font)
        self.btn_calculte.setObjectName("btn_calculte")
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset.setGeometry(QtCore.QRect(590, 270, 91, 31))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.btn_reset.setFont(font)
        self.btn_reset.setObjectName("btn_reset")
        self.btn_families = QtWidgets.QPushButton(self.centralwidget)
        self.btn_families.setGeometry(QtCore.QRect(550, 160, 241, 41))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.btn_families.setFont(font)
        self.btn_families.setObjectName("btn_families")
        self.btn_students = QtWidgets.QPushButton(self.centralwidget)
        self.btn_students.setGeometry(QtCore.QRect(290, 210, 241, 41))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.btn_students.setFont(font)
        self.btn_students.setObjectName("btn_students")
        self.btn_goldenAge = QtWidgets.QPushButton(self.centralwidget)
        self.btn_goldenAge.setGeometry(QtCore.QRect(550, 210, 241, 41))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.btn_goldenAge.setFont(font)
        self.btn_goldenAge.setObjectName("btn_goldenAge")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(290, 340, 71, 21))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.lbl_runtime = QtWidgets.QLabel(self.centralwidget)
        self.lbl_runtime.setGeometry(QtCore.QRect(360, 340, 133, 18))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.lbl_runtime.setFont(font)
        self.lbl_runtime.setObjectName("lbl_runtime")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(300, 410, 121, 21))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(320, 430, 61, 21))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(440, 420, 191, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_32 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_33)
        self.lbl_best1 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.lbl_best1.setFont(font)
        self.lbl_best1.setObjectName("lbl_best1")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_best1)
        self.lbl_worst1 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.lbl_worst1.setFont(font)
        self.lbl_worst1.setObjectName("lbl_worst1")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_worst1)
        self.lbl_best2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.lbl_best2.setFont(font)
        self.lbl_best2.setObjectName("lbl_best2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_best2)
        self.lbl_worst2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.lbl_worst2.setFont(font)
        self.lbl_worst2.setObjectName("lbl_worst2")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_worst2)
        self.lbl_best3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.lbl_best3.setFont(font)
        self.lbl_best3.setObjectName("lbl_best3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_best3)
        self.lbl_worst3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.lbl_worst3.setFont(font)
        self.lbl_worst3.setObjectName("lbl_worst3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lbl_worst3)
        self.btn_DB = QtWidgets.QPushButton(self.centralwidget)
        self.btn_DB.setGeometry(QtCore.QRect(650, 410, 131, 31))
        font = QtGui.QFont()
        font.setFamily("David")
        font.setPointSize(12)
        self.btn_DB.setFont(font)
        self.btn_DB.setObjectName("btn_DB")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        self.btn_DB.setEnabled(False)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.rdoButton2.toggled.connect(self.rdoButtonUpdate)
        self.rdoButton1.toggled.connect(self.rdoButtonUpdate)
        self.btn_reset.clicked.connect(self.resetValues)
        self.btn_students.clicked.connect(self.studentsClicked)
        self.btn_singles.clicked.connect(self.singlesClicked)
        self.btn_families.clicked.connect(self.familiesClicked)
        self.btn_goldenAge.clicked.connect(self.goldenAgeClicked)
        self.btn_calculte.clicked.connect(self.calculateClicked)
        self.btn_DB.clicked.connect(self.openExcelDB)


    def calculateClicked(self):
        self.topsis()
        self.btn_DB.setEnabled(True)
        testNum = self.cmbBox18.currentText()
        if int(testNum)>1:
            self.switchLabel()

    def openExcelDB(self):
        best1 = int(self.lbl_best1.text())
        best2 = int(self.lbl_best2.text())
        best3 = int(self.lbl_best3.text())
        worst1 = int(self.lbl_worst1.text())
        worst2 = int(self.lbl_worst2.text())
        worst3 = int(self.lbl_worst3.text())
        workbook = xlsxwriter.Workbook('Results.xlsx')
        worksheet = workbook.add_worksheet()
        worksheet.write('A2', 'Best')
        worksheet.write('A1', 'index_column')
        worksheet.write('B1', 'Appartment_Price')
        worksheet.write('C1', 'Amount_Of_Rooms')
        worksheet.write('D1', 'Location')
        worksheet.write('E1', 'Floor')
        worksheet.write('F1', 'Size')
        worksheet.write('G1', 'Parking')
        worksheet.write('H1', 'Air_Conditioner')
        worksheet.write('I1', 'Elevator')
        worksheet.write('J1', 'Warehouse')
        worksheet.write('K1', 'Garden')
        worksheet.write('L1', 'Safe_Room')
        worksheet.write('M1', 'Year_Of_Construction')
        worksheet.write('N1', 'Building_Committe_Price')
        worksheet.write('O1', 'Property_Tax')
        worksheet.write('P1', 'Devided_Appartment')
        worksheet.write('Q1', 'Roomates_Appropritate')
        worksheet.write('R1', 'Handicap_Accessible')
        worksheet.write('S1', 'Pandor_Doors')
        worksheet.write('T1', 'Window_Grating')
        worksheet.write('U1', 'Furnished')
        row = 2
        column = 0
        my_data = genfromtxt('Dataset.csv', delimiter=',', skip_header=1)
        content = my_data[best1]
        content2 = my_data[best2]
        content3 = my_data[best3]
        content4 = my_data[worst1]
        content5 = my_data[worst2]
        content6 = my_data[worst3]
        for item in content:
            worksheet.write(row, column, item)
            column += 1
        column = 0
        row = 3
        for item in content2:
            worksheet.write(row, column, item)
            column += 1
        column = 0
        row = 4
        for item in content3:
            worksheet.write(row, column, item)
            column += 1

        worksheet.write('A7', 'Worse')
        column = 0
        row = 7
        for item in content4:
            worksheet.write(row, column, item)
            column += 1
        column = 0
        row = 8
        for item in content5:
            worksheet.write(row, column, item)
            column += 1
        column = 0
        row = 9
        for item in content6:
            worksheet.write(row, column, item)
            column += 1
        workbook.close()
        os.chdir(sys.path[0])
        os.system('start excel.exe "%s\\Results.xlsx"' % (sys.path[0],))

    def goldenAgeClicked(self):
        if self.rdoButton2.isChecked():
            result = self.borda(4)
            max = result['results']
            bot_3_idx=np.argsort(max)[-48:]
            self.lbl_runtime.setText(str(result['time']))
            self.lbl_best1.setText(str(bot_3_idx[45]))
            self.lbl_best2.setText(str(bot_3_idx[46]))
            self.lbl_best3.setText(str(bot_3_idx[47]))
            self.lbl_worst1.setText(str(bot_3_idx[2]))
            self.lbl_worst2.setText(str(bot_3_idx[1]))
            self.lbl_worst3.setText(str(bot_3_idx[0]))
            self.btn_DB.setEnabled(True)
        else:
            self.cmbBox1.setCurrentIndex(3)
            self.cmbBox2.setCurrentIndex(3)
            self.cmbBox3.setCurrentIndex(2)
            self.cmbBox4.setCurrentIndex(2)
            self.cmbBox5.setCurrentIndex(2)
            self.cmbBox6.setCurrentIndex(4)
            self.cmbBox7.setCurrentIndex(3)
            self.cmbBox8.setCurrentIndex(3)
            self.cmbBox9.setCurrentIndex(2)
            self.cmbBox10.setCurrentIndex(4)
            self.cmbBox11.setCurrentIndex(4)
            self.cmbBox12.setCurrentIndex(1)
            self.cmbBox13.setCurrentIndex(1)
            self.cmbBox14.setCurrentIndex(1)
            self.cmbBox15.setCurrentIndex(0)
            self.cmbBox16.setCurrentIndex(0)
            self.cmbBox17.setCurrentIndex(4)
            self.cmbBox18.setCurrentIndex(3)
            self.cmbBox19.setCurrentIndex(1)
            self.cmbBox20.setCurrentIndex(3)

    def familiesClicked(self):                            
        if self.rdoButton2.isChecked():
            result = self.borda(3)
            max = result['results']
            bot_3_idx=np.argsort(max)[-48:]
            self.lbl_runtime.setText(str(result['time']))
            self.lbl_best1.setText(str(bot_3_idx[45]))
            self.lbl_best2.setText(str(bot_3_idx[46]))
            self.lbl_best3.setText(str(bot_3_idx[47]))
            self.lbl_worst1.setText(str(bot_3_idx[2]))
            self.lbl_worst2.setText(str(bot_3_idx[1]))
            self.lbl_worst3.setText(str(bot_3_idx[0]))
            self.btn_DB.setEnabled(True)
        else:
            self.cmbBox1.setCurrentIndex(2)
            self.cmbBox2.setCurrentIndex(4)
            self.cmbBox3.setCurrentIndex(2)
            self.cmbBox4.setCurrentIndex(2)
            self.cmbBox5.setCurrentIndex(4)
            self.cmbBox6.setCurrentIndex(4)
            self.cmbBox7.setCurrentIndex(3)
            self.cmbBox8.setCurrentIndex(3)
            self.cmbBox9.setCurrentIndex(4)
            self.cmbBox10.setCurrentIndex(2)
            self.cmbBox11.setCurrentIndex(4)
            self.cmbBox12.setCurrentIndex(1)
            self.cmbBox13.setCurrentIndex(1)
            self.cmbBox14.setCurrentIndex(1)
            self.cmbBox15.setCurrentIndex(0)
            self.cmbBox16.setCurrentIndex(0)
            self.cmbBox17.setCurrentIndex(1)
            self.cmbBox18.setCurrentIndex(2)
            self.cmbBox19.setCurrentIndex(2)
            self.cmbBox20.setCurrentIndex(0)

    def singlesClicked(self):
        if self.rdoButton2.isChecked():
            result = self.borda(2)
            max = result['results']
            bot_3_idx=np.argsort(max)[-48:]
            self.lbl_runtime.setText(str(result['time']))
            self.lbl_best1.setText(str(bot_3_idx[45]))
            self.lbl_best2.setText(str(bot_3_idx[46]))
            self.lbl_best3.setText(str(bot_3_idx[47]))
            self.lbl_worst1.setText(str(bot_3_idx[2]))         
            self.lbl_worst2.setText(str(bot_3_idx[1]))
            self.lbl_worst3.setText(str(bot_3_idx[0]))
            self.btn_DB.setEnabled(True)
        else:
            self.cmbBox1.setCurrentIndex(4)
            self.cmbBox2.setCurrentIndex(1)
            self.cmbBox3.setCurrentIndex(4)
            self.cmbBox4.setCurrentIndex(0)
            self.cmbBox5.setCurrentIndex(1)
            self.cmbBox6.setCurrentIndex(2)
            self.cmbBox7.setCurrentIndex(4)
            self.cmbBox8.setCurrentIndex(1)
            self.cmbBox9.setCurrentIndex(0)
            self.cmbBox10.setCurrentIndex(0)
            self.cmbBox11.setCurrentIndex(0)
            self.cmbBox12.setCurrentIndex(0)
            self.cmbBox13.setCurrentIndex(3)
            self.cmbBox14.setCurrentIndex(4)
            self.cmbBox15.setCurrentIndex(2)
            self.cmbBox16.setCurrentIndex(0)
            self.cmbBox17.setCurrentIndex(0)
            self.cmbBox18.setCurrentIndex(0)
            self.cmbBox19.setCurrentIndex(0)
            self.cmbBox20.setCurrentIndex(3)

    def studentsClicked(self):
        if self.rdoButton2.isChecked():
            result = self.borda(1)
            max = result['results']
            bot_3_idx=np.argsort(max)[-48:]
            self.lbl_runtime.setText(str(result['time']))
            self.lbl_best1.setText(str(bot_3_idx[45]))
            self.lbl_best2.setText(str(bot_3_idx[46]))
            self.lbl_best3.setText(str(bot_3_idx[47]))
            self.lbl_worst1.setText(str(bot_3_idx[2]))
            self.lbl_worst2.setText(str(bot_3_idx[1]))
            self.lbl_worst3.setText(str(bot_3_idx[0]))
            self.btn_DB.setEnabled(True)
        else:
            self.cmbBox1.setCurrentIndex(4)
            self.cmbBox2.setCurrentIndex(2)
            self.cmbBox3.setCurrentIndex(4)
            self.cmbBox4.setCurrentIndex(0)
            self.cmbBox5.setCurrentIndex(1)
            self.cmbBox6.setCurrentIndex(2)
            self.cmbBox7.setCurrentIndex(4)
            self.cmbBox8.setCurrentIndex(0)
            self.cmbBox9.setCurrentIndex(0)
            self.cmbBox10.setCurrentIndex(0)
            self.cmbBox11.setCurrentIndex(0)
            self.cmbBox12.setCurrentIndex(0)
            self.cmbBox13.setCurrentIndex(2)
            self.cmbBox14.setCurrentIndex(3)
            self.cmbBox15.setCurrentIndex(3)
            self.cmbBox16.setCurrentIndex(4)
            self.cmbBox17.setCurrentIndex(0)
            self.cmbBox18.setCurrentIndex(0)
            self.cmbBox19.setCurrentIndex(0)
            self.cmbBox20.setCurrentIndex(1)
            
    def resetValues(self):
        self.btn_DB.setEnabled(False)
        self.cmbBox1.setCurrentIndex(0)
        self.cmbBox2.setCurrentIndex(0)
        self.cmbBox3.setCurrentIndex(0)
        self.cmbBox4.setCurrentIndex(0)
        self.cmbBox5.setCurrentIndex(0)
        self.cmbBox6.setCurrentIndex(0)
        self.cmbBox7.setCurrentIndex(0)
        self.cmbBox8.setCurrentIndex(0)
        self.cmbBox9.setCurrentIndex(0)
        self.cmbBox10.setCurrentIndex(0)
        self.cmbBox11.setCurrentIndex(0)
        self.cmbBox12.setCurrentIndex(0)
        self.cmbBox13.setCurrentIndex(0)
        self.cmbBox14.setCurrentIndex(0)
        self.cmbBox15.setCurrentIndex(0)
        self.cmbBox16.setCurrentIndex(0)
        self.cmbBox17.setCurrentIndex(0)
        self.cmbBox18.setCurrentIndex(0)
        self.cmbBox19.setCurrentIndex(0)
        self.cmbBox20.setCurrentIndex(0)
        self.lbl_runtime.setText("XXXXXXXXXXX")
        self.lbl_worst1.setText("First")
        self.lbl_worst2.setText("Second")
        self.lbl_worst3.setText("Third")
        self.lbl_best1.setText("First")
        self.lbl_best2.setText("Second")
        self.lbl_best3.setText("Third")

    def rdoButtonUpdate(self):
        if self.rdoButton2.isChecked():
            self.cmbBox1.setEnabled(False)
            self.cmbBox2.setEnabled(False)
            self.cmbBox3.setEnabled(False)
            self.cmbBox4.setEnabled(False)
            self.cmbBox5.setEnabled(False)
            self.cmbBox6.setEnabled(False)
            self.cmbBox7.setEnabled(False)
            self.cmbBox8.setEnabled(False)
            self.cmbBox9.setEnabled(False)
            self.cmbBox10.setEnabled(False)
            self.cmbBox11.setEnabled(False)
            self.cmbBox12.setEnabled(False)
            self.cmbBox13.setEnabled(False)
            self.cmbBox14.setEnabled(False)
            self.cmbBox15.setEnabled(False)
            self.cmbBox16.setEnabled(False)
            self.cmbBox17.setEnabled(False)
            self.cmbBox18.setEnabled(False)
            self.cmbBox19.setEnabled(False)
            self.cmbBox20.setEnabled(False)
            self.btn_calculte.setEnabled(False)
            self.btn_reset.setEnabled(False)
            self.resetValues()

        if self.rdoButton1.isChecked():
            self.btn_reset.setEnabled(True)
            self.btn_calculte.setEnabled(True)
            self.cmbBox1.setEnabled(True)
            self.cmbBox2.setEnabled(True)
            self.cmbBox3.setEnabled(True)
            self.cmbBox4.setEnabled(True)
            self.cmbBox5.setEnabled(True)
            self.cmbBox6.setEnabled(True)
            self.cmbBox7.setEnabled(True)
            self.cmbBox8.setEnabled(True)
            self.cmbBox9.setEnabled(True)
            self.cmbBox10.setEnabled(True)
            self.cmbBox11.setEnabled(True)
            self.cmbBox12.setEnabled(True)
            self.cmbBox13.setEnabled(True)
            self.cmbBox14.setEnabled(True)
            self.cmbBox15.setEnabled(True)
            self.cmbBox16.setEnabled(True)
            self.cmbBox17.setEnabled(True)
            self.cmbBox18.setEnabled(True)
            self.cmbBox19.setEnabled(True)
            self.cmbBox20.setEnabled(True)
            self.resetValues()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Parameters"))
        self.label.setText(_translate("MainWindow", "Criteria"))
        self.label_3.setText(_translate("MainWindow", "Appartament Price"))
        self.cmbBox1.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox1.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox1.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox1.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox1.setItemText(4, _translate("MainWindow", "5"))
        self.label_2.setText(_translate("MainWindow", "Weight"))
        self.label_4.setText(_translate("MainWindow", "Amount of Rooms"))
        self.label_5.setText(_translate("MainWindow", "Location"))
        self.label_6.setText(_translate("MainWindow", "Floor"))
        self.label_7.setText(_translate("MainWindow", "Size"))
        self.label_8.setText(_translate("MainWindow", "Parking"))
        self.label_9.setText(_translate("MainWindow", "Air conditioner"))
        self.label_10.setText(_translate("MainWindow", "Elevator"))
        self.label_11.setText(_translate("MainWindow", "Warehouse"))
        self.label_12.setText(_translate("MainWindow", "Garden"))
        self.label_13.setText(_translate("MainWindow", "Safe Room"))
        self.label_14.setText(_translate("MainWindow", "Year of Construction"))
        self.label_15.setText(_translate("MainWindow", "Building Committe Price"))
        self.label_16.setText(_translate("MainWindow", "Property Tax "))
        self.label_17.setText(_translate("MainWindow", "Divided appartament"))
        self.label_18.setText(_translate("MainWindow", "Roomates Appropriate"))
        self.label_19.setText(_translate("MainWindow", "Handicap Accessible"))
        self.label_20.setText(_translate("MainWindow", "Pandor Doors"))
        self.label_21.setText(_translate("MainWindow", "Window Grating"))
        self.label_22.setText(_translate("MainWindow", "Furnished"))
        self.cmbBox2.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox2.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox2.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox2.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox2.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox3.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox3.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox3.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox3.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox3.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox4.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox4.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox4.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox4.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox4.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox5.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox5.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox5.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox5.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox5.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox6.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox6.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox6.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox6.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox6.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox7.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox7.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox7.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox7.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox7.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox8.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox8.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox8.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox8.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox8.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox9.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox9.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox9.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox9.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox9.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox10.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox10.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox10.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox10.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox10.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox11.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox11.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox11.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox11.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox11.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox12.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox12.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox12.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox12.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox12.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox13.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox13.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox13.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox13.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox13.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox14.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox14.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox14.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox14.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox14.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox15.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox15.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox15.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox15.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox15.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox16.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox16.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox16.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox16.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox16.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox17.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox17.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox17.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox17.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox17.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox18.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox18.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox18.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox18.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox18.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox19.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox19.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox19.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox19.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox19.setItemText(4, _translate("MainWindow", "5"))
        self.cmbBox20.setItemText(0, _translate("MainWindow", "1"))
        self.cmbBox20.setItemText(1, _translate("MainWindow", "2"))
        self.cmbBox20.setItemText(2, _translate("MainWindow", "3"))
        self.cmbBox20.setItemText(3, _translate("MainWindow", "4"))
        self.cmbBox20.setItemText(4, _translate("MainWindow", "5"))
        self.label_24.setText(_translate("MainWindow", "Appartament Selector - TopSIS and Borda "))
        self.label_25.setText(_translate("MainWindow", "Implementation - Rank from 1 - 5"))
        self.rdoButton1.setText(_translate("MainWindow", "TopSIS"))
        self.rdoButton2.setText(_translate("MainWindow", "Borda"))
        self.btn_singles.setText(_translate("MainWindow", "Singles"))
        self.btn_calculte.setText(_translate("MainWindow", "Calculate"))
        self.btn_reset.setText(_translate("MainWindow", "Reset"))
        self.btn_families.setText(_translate("MainWindow", "Families"))
        self.btn_students.setText(_translate("MainWindow", "Students"))
        self.btn_goldenAge.setText(_translate("MainWindow", "Golden Age"))
        self.label_23.setText(_translate("MainWindow", "Runtime : "))
        self.lbl_runtime.setText(_translate("MainWindow", "XXXXXXXXXXXXXXXXXXXXXXXXX"))
        self.label_30.setText(_translate("MainWindow", "Houses according"))
        self.label_31.setText(_translate("MainWindow", "to indexs"))
        self.label_32.setText(_translate("MainWindow", "Best Results"))
        self.label_33.setText(_translate("MainWindow", "Worse Results"))
        self.lbl_best1.setText(_translate("MainWindow", "First"))
        self.lbl_worst1.setText(_translate("MainWindow", "First"))
        self.lbl_best2.setText(_translate("MainWindow", "Second"))
        self.lbl_worst2.setText(_translate("MainWindow", "Second"))
        self.lbl_best3.setText(_translate("MainWindow", "Third"))
        self.lbl_worst3.setText(_translate("MainWindow", "Third"))
        self.btn_DB.setText(_translate("MainWindow", "Open DataBase"))

    def topsis(self):
        start = datetime.now()
        weight=[self.cmbBox1.currentText(),self.cmbBox2.currentText(),self.cmbBox3.currentText(),self.cmbBox4.currentText(),self.cmbBox5.currentText()
                ,self.cmbBox6.currentText(),self.cmbBox7.currentText(),self.cmbBox8.currentText(),self.cmbBox9.currentText(),self.cmbBox10.currentText()
                ,self.cmbBox11.currentText(),self.cmbBox12.currentText(),self.cmbBox13.currentText(),self.cmbBox14.currentText(),self.cmbBox15.currentText()
                ,self.cmbBox16.currentText(),self.cmbBox17.currentText(),self.cmbBox18.currentText(),self.cmbBox19.currentText(),self.cmbBox20.currentText()]
        my_data = genfromtxt('Normalized.csv', delimiter=',', skip_header=1)
        for i in range(20):
            current_weight = weight[i]
            for j in range(48):
                my_data[j][i] = (my_data[j][i]*int(current_weight))
        maxInColumns=np.amax(my_data,axis=0)
        minInColumns=np.amin(my_data,axis=0)
        for i in range(48):
            x = 0
            y = 0
            for j in range(20):
                x = x + ((my_data[i][j] - maxInColumns[j])*(my_data[i][j] - maxInColumns[j]))
                y = y + ((my_data[i][j] - minInColumns[j])*(my_data[i][j] - minInColumns[j]))
            x=math.sqrt(x)
            y=math.sqrt(y)
            my_data[i][20] = y / (x + y)
        tempArray = my_data[:,20]
        bot_3_idx=np.argsort(tempArray)[-48:]
        self.lbl_worst1.setText(str(bot_3_idx[45]))
        self.lbl_worst2.setText(str(bot_3_idx[46]))
        self.lbl_worst3.setText(str(bot_3_idx[47]))
        self.lbl_best1.setText(str(bot_3_idx[2]))
        self.lbl_best2.setText(str(bot_3_idx[1]))
        self.lbl_best3.setText(str(bot_3_idx[0]))
        total_time = datetime.now() - start
        seconds = total_time.microseconds
        seconds = (seconds/10000)
        self.lbl_runtime.setText(str(seconds))

    def switchLabel(self):
        text1= self.lbl_worst1.text()
        text2 = self.lbl_worst2.text()
        text3 = self.lbl_worst3.text()
        self.lbl_worst1.setText(self.lbl_best1.text())
        self.lbl_worst2.setText(self.lbl_best2.text())
        self.lbl_worst3.setText(self.lbl_best3.text())
        self.lbl_best1.setText(text1)
        self.lbl_best2.setText(text2)
        self.lbl_best3.setText(text3)

    def borda(self,number):
        start=datetime.now()
        table = [
            [48, 22, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 47, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1],  # Student alex
            [40, 30, 2, 43, 47, 46, 45, 44, 48, 39, 38, 37, 36, 35, 34, 33, 32, 31, 47, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 42, 1],  # Student snir
            [40, 39, 38, 37, 36, 35, 34, 48, 47, 46, 45, 44, 43, 42, 41, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1],  # singles alex
            [25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1],  # singles snir
            [14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15],  # families alex
            [25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26],  # families snir
            [35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36],  # go alex
            [48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]]  # go snir
        score_res = []
        if(number == 1):
            for i in range(48):
                score_res.append(table[0][i]+table[1][i])
        if(number == 2):
            for i in range(48):
                score_res.append(table[2][i]+table[3][i])
        if(number == 3):
            for i in range(48):
                score_res.append(table[4][i]+table[5][i])
        if(number == 4):
            for i in range(48):
                score_res.append(table[6][i]+table[7][i])
        time.sleep(0.5)
        total_time = datetime.now()-start
        seconds=total_time.microseconds
        return {"results":score_res,"time":((seconds/1000)-500)}

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
